/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Platform {
  Default = 0,
  Pc = 12,
  Ps3 = 10,
  Xbox360 = 11
}
export const enum PixelFormat {
  Dxt1 = 0,
  Dxt3 = 1,
  Dxt5 = 2,
  Rgba = 4,
  Rgb = 5,
  Unknown = 7
}
export const enum TextureType {
  OneD = 0,
  TwoD = 1,
  ThreeD = 2,
  CubeMapped = 3
}
export interface CompileDstexParams {
  platform?: Platform
  pixelFormat?: PixelFormat
  textureType?: TextureType
  premultiplyAlpha?: boolean
  algorithm?: number
  weighColourByAlpha?: boolean
}
export declare function compileDstex(width: number, height: number, rgbaData: Buffer, params?: CompileDstexParams | undefined | null, generateMipmaps?: boolean | undefined | null): Uint8Array
